# -*- coding: utf-8 -*-
"""excel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2vZhN7EY6jTpKIFBK0cmQqchSsK7vEK
"""

def excel_col_num(col_name):
    col_name = col_name.upper()
    result = 0
    for i in col_name:
        value = ord(i) - ord('A') + 1
        result = result * 26 + value
    return result

col_name=input("enter column name [A - XFD]:")
print(excel_col_num(col_name))